export const productData = [
  {
    id: 1,
    src: 'assets/p1.png',
    name: 'Emerald stone set',
    price: '2,250',
    type: 'pnt',
  },
  {
    id: 2,
    src: 'assets/p2.png',
    name: 'Bridal Set',
    price: '3,050',
    type: 'pnt',
  },
  {
    id: 3,
    src: 'assets/p3.png',
    name: 'Gold Necklase',
    price: '2,050',
    type: 'pnt',
  },
  {
    id: 4,
    src: 'assets/p4.png',
    name: 'Wide Gold Chain',
    price: '2,050',
    type: 'pnt',
  },
  {
    id: 5,
    src: 'assets/p5.png',
    name: 'Diamond Stud',
    price: '3,000',
    type: 'pnt',
  },
  {
    id: 6,
    src: 'assets/p6.png',
    name: 'Diamond cut Ring',
    price: '2,500',
    type: 'pnt',
  },
  {
    id: 7,
    src: 'assets/p7.png',
    name: 'Rose & white Gold',
    price: '2,500',
    type: 'pnt',
  },
  {
    id: 8,
    src: 'assets/p8.png',
    name: 'Gold Hoop Earring',
    price: '1,500',
    type: 'pnt',
  },
  {
    id: 9,
    src: 'assets/trend1.png',
    name: 'Pearl necklase',
    price: '1,500',
    type: 'trend',
  },
  {
    id: 10,
    src: 'assets/trend2.png',
    name: 'Gold Checker',
    price: '1,800',
    type: 'trend',
  },
  {
    id: 11,
    src: 'assets/trend3.png',
    name: 'Diamond Drop',
    price: '1850',
    type: 'trend',
  },
  {
    id: 12,
    src: 'assets/trend4.png',
    name: 'Pearl Stud',
    price: '1,250',
    type: 'trend',
  },
  {
    id: 13,
    src: 'assets/trend5.png',
    name: 'Gem Stone',
    price: '1250',
    type: 'trend',
  },
  {
    id: 14,
    src: 'assets/trend6.png',
    name: 'Gold Bracelet Stack',
    price: '1,150',
    type: 'trend',
  },
  {
    id: 15,
    src: 'assets/trend7.png',
    name: '2-stone Ring',
    price: '850',
    type: 'trend',
  },
  {
    id: 16,
    src: 'assets/trend8.png',
    name: 'Princess cut',
    price: '850',
    type: 'trend',
  },
]

export const btnData = [
  { id: 1, name: 'Description' },

  {
    id: 2,
    name: 'Warranty',
  },
]
